stages:
  prepare:
    cmd: echo "Verificando que los datos existen..."
    deps:
      - data/iris_dataset.csv
  train:
    cmd: python src/train.py --n_estimators ${train.n_estimators}
    deps:
      - src/train.py
      - requirements.txt
      - data/iris_dataset.csv
    outs:
      - results/model.pkl
      - results/confusion_matrix.png
    metrics:
      - results/mlflow_metrics.json
    params:
      - train.n_estimators
